(()=>{
"use strict";
const tracker=window.HistProgress,remote=window.RemoteTracker,TEST_SIZE=20;
const ui={start:document.getElementById("testStart"),activity:document.getElementById("testActivity"),card:document.getElementById("testCard"),progress:document.getElementById("testProgress"),unit:document.getElementById("testUnit"),summary:document.getElementById("testRangeSummary"),title:document.getElementById("testTitle")};
let state={};
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const unitKey=u=>`unit${u}`;
function sectionsFor(u){return Object.values(window.ALL_SECTIONS||{}).filter(s=>Number(s.unit)===Number(u)).sort((a,b)=>a.id.localeCompare(b.id,undefined,{numeric:true}))}
function prepared(q,s){const tagged=q.choices.map((text,i)=>({text,ok:i===q.answer})),choices=shuffle(tagged);return {...q,unit:s.unit,section:s.id,sectionTitle:s.title,trackingKey:`${s.unit}:${s.id}:${q.id}`,choices:choices.map(x=>x.text),answer:choices.findIndex(x=>x.ok)}}
function category(item,h){const r=h[`${item.section.id}:${item.question.id}`];if(!r||!r.timesSeen)return"unseen";const n=(r.timesCorrect||0)+(r.timesIncorrect||0);return r.lastResult==="incorrect"||(n&&(r.timesCorrect||0)/n<.8)?"weak":"known"}
function score(item,h,recent){const k=`${item.section.id}:${item.question.id}`,r=h[k];let n=Math.random()*12+(item.question.style==="casey"?24:0);if(!r||!r.timesSeen)n+=55;else if(category(item,h)==="weak")n+=70;else n+=20;if(recent.has(k))n-=35;return n}
function build(u,maxSection){const sections=sectionsFor(u).filter(s=>!maxSection||s.id.localeCompare(maxSection,undefined,{numeric:true})<=0),history=tracker?tracker.getUnitData(unitKey(u)):{questions:{},testAttempts:[]},recent=new Set((history.testAttempts||[]).slice(-2).flatMap(a=>a.questionKeys||[])),quota=Math.floor(TEST_SIZE/sections.length),extra=TEST_SIZE%sections.length,picked=[];sections.forEach((s,i)=>{let count=quota+(i<extra?1:0),pool=s.questions.map(q=>({section:s,question:q}));let coreTarget=Math.min(count,Math.max(1,Math.round(count*.8)));const take=filter=>{const candidates=pool.filter(x=>!picked.includes(x)&&filter(x)).sort((a,b)=>score(b,history.questions||{},recent)-score(a,history.questions||{},recent));return candidates.shift()};while(count){let x=coreTarget>0?take(x=>x.question.style!=="deeper"):take(()=>true);if(!x)x=take(()=>true);if(!x)break;picked.push(x);if(x.question.style!=="deeper")coreTarget--;count--}});return shuffle(picked.slice(0,TEST_SIZE).map(x=>prepared(x.question,x.section)))}
function begin(){const unit=Number(ui.unit.value),questions=build(unit),attempt=(tracker?tracker.getUnitData(unitKey(unit)).testAttempts.length:0)+1;state={unit,questions,index:0,answers:Array(questions.length).fill(null),retryAnswers:{},phase:"test",attempt,activityId:`unit${unit}-test-${Date.now()}`,startedAt:Date.now(),seen:new Set(),notice:""};document.body.dataset.unit=unit;document.querySelector(".test-shell")?.classList.remove("review-mode");ui.card.className="activity-card";ui.title.textContent=`Unit ${unit} Practice Test`;ui.start.classList.add("hidden");ui.activity.classList.remove("hidden");remote?.track({unit:`Unit ${unit}`,mode:"test",event_type:"test_started",activity_id:state.activityId,details:{attempt,selected_question_ids:questions.map(q=>q.trackingKey)}});renderTest()}
function renderTest(){const q=state.questions[state.index];seen(q);ui.progress.textContent=`${state.index+1} of ${state.questions.length} · ${state.answers.filter(x=>x!==null).length} answered`;ui.card.innerHTML=`<p class="eyebrow">UNIT ${q.unit} · SECTION ${esc(q.section)} · ${esc(q.sectionTitle)}</p><h2>${esc(q.q)}</h2>${state.notice?`<div class="test-notice" role="status">${esc(state.notice)}</div>`:""}<div class="choices">${q.choices.map((c,i)=>`<button class="choice ${state.answers[state.index]===i?"selected":""}" data-choice="${i}" aria-pressed="${state.answers[state.index]===i}">${esc(c)}</button>`).join("")}</div><div class="actions"><button class="secondary" id="prev" ${state.index===0?"disabled":""}>← Previous</button><button class="primary" id="next">${state.index===state.questions.length-1?"Submit Test":"Next →"}</button></div>`;ui.card.querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{state.answers[state.index]=Number(b.dataset.choice);state.notice="";renderTest()});document.getElementById("prev").onclick=()=>{state.index--;renderTest()};document.getElementById("next").onclick=()=>{if(state.index<state.questions.length-1){state.index++;renderTest();return}const x=state.answers.findIndex(a=>a===null);if(x>=0){state.index=x;state.notice="Answer every question before submitting.";renderTest()}else scoreOriginal()}}
function scoreOriginal(){state.original=state.questions.map((q,i)=>({correct:state.answers[i]===q.answer}));state.questions.forEach((q,i)=>{tracker?.recordAnswer(q.section,q.id,state.original[i].correct,unitKey(state.unit));remote?.track({unit:`Unit ${state.unit}`,section:q.section,mode:"test",event_type:"test_question_scored",activity_id:state.activityId,question_id:q.id,result:state.original[i].correct?"correct":"incorrect",details:{attempt:state.attempt,selected_choice:state.answers[i],correct_choice:q.answer}})});state.missed=state.original.map((x,i)=>x.correct?null:i).filter(x=>x!==null);if(state.missed.length){state.phase="retry";state.retryIndex=0;renderRetry()}else finishAndReview()}
function renderRetry(){const qi=state.missed[state.retryIndex],q=state.questions[qi],wrong=state.answers[qi];ui.progress.textContent=`Retry ${state.retryIndex+1} of ${state.missed.length}`;ui.card.innerHTML=`<p class="eyebrow">STAGE 1 · RETRY MISSED QUESTION ${qi+1}</p><h2>${esc(q.q)}</h2><p>Try again. Your original answer is crossed out; the correct answer has not been revealed.</p><div class="choices">${q.choices.map((c,i)=>`<button class="choice ${i===wrong?"original-wrong":""}" data-retry="${i}" ${i===wrong?"disabled":""}>${esc(c)}${i===wrong?'<span class="choice-marker">Original answer</span>':""}</button>`).join("")}</div><div class="actions"><button class="primary" id="saveRetry" disabled>Save Retry →</button></div>`;let selected=null;ui.card.querySelectorAll("[data-retry]:not([disabled])").forEach(b=>b.onclick=()=>{selected=Number(b.dataset.retry);ui.card.querySelectorAll("[data-retry]").forEach(x=>x.classList.toggle("selected",Number(x.dataset.retry)===selected));document.getElementById("saveRetry").disabled=false});document.getElementById("saveRetry").onclick=()=>{state.retryAnswers[qi]=selected;const ok=selected===q.answer;remote?.track({unit:`Unit ${state.unit}`,section:q.section,mode:"test_review",event_type:"test_retry_scored",activity_id:state.activityId,question_id:q.id,result:ok?"retry_correct":"retry_incorrect",details:{original_choice:wrong,retry_choice:selected,correct_choice:q.answer}});state.retryIndex++;state.retryIndex<state.missed.length?renderRetry():finishAndReview()}}
function finishAndReview(){const correct=state.original.filter(x=>x.correct).length,pct=Math.round(correct/state.questions.length*100),retryAttempted=state.missed?.length||0,retryCorrect=Object.entries(state.retryAnswers).filter(([i,a])=>a===state.questions[i].answer).length,stats={};state.questions.forEach((q,i)=>{stats[q.section]??={title:q.sectionTitle,correct:0,total:0};stats[q.section].total++;if(state.original[i].correct)stats[q.section].correct++});tracker?.recordTestAttempt({timestamp:new Date().toISOString(),score:correct,total:state.questions.length,percentage:pct,questionKeys:state.questions.map(q=>`${q.section}:${q.id}`),sectionResults:stats,retryResults:state.retryAnswers},unitKey(state.unit));remote?.track({unit:`Unit ${state.unit}`,mode:"test",event_type:"test_completed",activity_id:state.activityId,score_earned:correct,score_possible:state.questions.length,percent:pct,duration_seconds:Math.round((Date.now()-state.startedAt)/1000),details:{attempt:state.attempt,score_type:"original_test_score",original_score:correct,original_total:state.questions.length,original_percent:pct,retry_attempted:retryAttempted,retry_correct:retryCorrect,retry_remaining_incorrect:Math.max(0,retryAttempted-retryCorrect)}});state.phase="review";state.reviewSection=state.questions[0].section;renderReview()}
function renderReview(){const relevant=sectionsFor(state.unit);ui.progress.textContent="Stage 2 · Full Test + Learn Review";document.querySelector(".test-shell")?.classList.add("review-mode");ui.card.className="activity-card review-wide";ui.card.innerHTML=`<div class="review-score"><p class="eyebrow">UNIT ${state.unit} RESULTS</p><strong>${state.original.filter(x=>x.correct).length}/${state.questions.length}</strong><span>Original score</span></div><div class="review-layout"><div class="review-questions" id="reviewQuestions">${state.questions.map((q,i)=>reviewItem(q,i)).join("")}</div><aside class="learn-pane"><label for="learnSection"><strong>Learn section</strong></label><select id="learnSection">${relevant.map(s=>`<option value="${esc(s.id)}" ${s.id===state.reviewSection?"selected":""}>${esc(s.id)} · ${esc(s.title)}</option>`).join("")}</select><div id="learnContent"></div></aside></div><div class="actions"><button class="secondary" id="retryTest">Try Another 20</button><a class="primary button-link" href="index.html">Course Home</a></div>`;ui.card.querySelectorAll("[data-section]").forEach(b=>b.onclick=()=>loadLearn(b.dataset.section));document.getElementById("learnSection").onchange=e=>loadLearn(e.target.value);document.getElementById("retryTest").onclick=()=>location.reload();loadLearn(state.reviewSection);remote?.track({unit:`Unit ${state.unit}`,mode:"test_review",event_type:"full_review_opened",activity_id:state.activityId})}
function reviewItem(q,i){const first=state.original[i].correct,retry=state.retryAnswers[i],retryOk=retry===q.answer,status=first?"correct-first":retryOk?"corrected-retry":"still-incorrect",label=first?"✓ Correct first attempt":retryOk?"✓ Corrected on retry":"✗ Still needs review";return `<article class="test-review-item ${status}"><button class="review-question-link" data-section="${esc(q.section)}"><span class="eyebrow">QUESTION ${i+1}</span><strong>Unit ${q.unit} · Section ${esc(q.section)} — ${esc(q.sectionTitle)}</strong></button><h3>${esc(q.q)}</h3><p class="review-status">${label}</p><p><strong>Original answer:</strong> ${esc(q.choices[state.answers[i]])}</p>${retry!==undefined?`<p><strong>Retry answer:</strong> ${esc(q.choices[retry])}</p>`:""}<p><strong>Correct answer:</strong> ${esc(q.choices[q.answer])}</p><p class="review-explanation"><strong>Explanation:</strong> ${esc(q.explanation)}</p></article>`}
function loadLearn(id){state.reviewSection=id;const s=sectionsFor(state.unit).find(x=>x.id===id);if(!s)return;document.getElementById("learnSection").value=id;document.getElementById("learnContent").innerHTML=`<h2>${esc(s.id)} ${esc(s.title)}</h2>${s.learnScreens.map(x=>`<section class="learn-review-screen"><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><ul>${(x.know||[]).map(k=>`<li>${esc(k)}</li>`).join("")}</ul></section>`).join("")}`;remote?.track({unit:`Unit ${state.unit}`,section:id,mode:"test_review",event_type:"learn_section_reviewed",activity_id:state.activityId})}
function seen(q){if(state.seen.has(q.trackingKey))return;state.seen.add(q.trackingKey);tracker?.recordSeen(q.section,q.id,unitKey(state.unit))}
function update(){const ss=sectionsFor(Number(ui.unit.value));ui.summary.textContent=`20 questions balanced across ${ss.length} sections. Approximately 80% Casey-style core and 20% deeper understanding.`}
document.getElementById("startTest").onclick=begin;ui.unit.onchange=update;update();document.getElementById("exitTest").onclick=()=>{if(confirm("Exit this test? Current answers will be cleared."))location.href="index.html"};remote?.track({mode:"test",event_type:"test_mode_opened"});
window.CourseTestSelection={build};
window.Unit1TestSelection={buildSmartTest:maxSection=>build(1,maxSection)};
})();
